version: '3'
services:
  frontend:
    build:
      context: ./my-app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    env_file: 
      - ./my-app/.env  # Указываем путь к .env файлу клиента

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env  # Указываем путь к .env файлу сервера

